import "./globals.css";
import type { Metadata } from "next";
import AuthSession from "./utils/AuthSession";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body>
        <AuthSession>
          <Header />
          {children}
        </AuthSession>
      </body>
    </html>
  );
}
