import "./globals.css";
import type { Metadata } from "next";
import AuthSession from "./utils/AuthSession";
import Header from "./components/Header";
import Navbar from "./components/Navbar";
import Providers from "@/lib/providers";
import Offcanvas from "./components/Offcanvas";
import DarkMode from "./components/DarkMode";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AuthSession>
            <Header />
            {/* <Navbar /> */}
            {/* <Offcanvas /> */}
            {children}
            <DarkMode />
          </AuthSession>
        </Providers>
      </body>
    </html>
  );
}
